In [5]:
import torch

Q1: What are tensors?

Ans: At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number.


In [3]:
# Number
t1 = torch.tensor(4.0)
t1

tensor(4.)

Here 4. simply represents 4.0 as a shorthand and can be verified by checking 'dtype' attribute of tensor.


In [4]:
t1.dtype

torch.float32

Here are some more complex tensors formed from 'Vector', 'Matrics' and 3D-array.


In [5]:
# Vector
t2 = torch.tensor([1.0, 2, 3, 8])
t2

tensor([1., 2., 3., 8.])

In [6]:
# Matrix
t3 = torch.tensor([[6, 9], [2, 6], [9, 23]])
t3

tensor([[ 6,  9],
        [ 2,  6],
        [ 9, 23]])

In [7]:
t4 = torch.tensor(([[[11, 12, 13],
                     [13, 14, 15]],
                    [[15, 16, 17],
                     [17, 18, 19]]]))
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

#### Random Tensors and Seeding:

'torch.manual_seed()' Initialize tensors, such as a model’s learning weights, with random values is common but there are times - especially in research settings - where you’ll want some assurance of the reproducibility of your results. Manually setting your random number generator’s seed is the way to do this. Let’s look more closely:


In [8]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


above is that random1 and random3 carry identical values, as do random2 and random4. Manually setting the RNG’s seed resets it, so that identical computations depending on random number should, in most settings, provide identical results.


### Shape property:

Tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the '.shape' property of a tensor.


In [9]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [10]:
print(t2)
t2.shape

tensor([1., 2., 3., 8.])


torch.Size([4])

In [11]:
print(t3)
t3.shape

tensor([[ 6,  9],
        [ 2,  6],
        [ 9, 23]])


torch.Size([3, 2])

In [12]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

Tensor operations and gradients:

We can combine tensors with the usual arithmetic operations. Let's look an example:

In [18]:
x =  torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

About "required_grad" attribute:

In PyTorch, requires_grad=True is a boolean attribute that indicates whether a tensor’s gradients should be computed and stored during the backward pass of the computation graph. When a tensor has requires_grad=True, it means that:

The tensor’s values will be tracked and updated during the forward pass.
The tensor’s gradients will be computed and stored during the backward pass.
The tensor’s gradients will be used to update the model’s parameters during optimization (e.g., during training).
In other words, when requires_grad=True, the tensor is considered a “leaf” node in the computation graph, meaning that its values are inputs to the computation, and its gradients will be propagated back to the model’s parameters.

=> Let's create a new tensor y by combining these tensors:

In [14]:
# Airthmatic operations

y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch special is that we can automatically compute the derivative of 'y' w.r.t. the tensors that have 'requires_grad' set to True i.e. 'w' and 'b'. To compute the derivatives, we can call the '.backward' method on our result y.

In [15]:
# Compute
y.backward()

The derivates of y w.r.t the input tensors are stored in the .grad property of the respective tensors.

In [17]:
# Display Gradients

print('dy/dx = ', x.grad)
print('dy/dw = ', w.grad)
print('dy/db = ', b.grad)

dy/dx =  None
dy/dw =  tensor(3.)
dy/db =  tensor(1.)


![picture 0](images/918befda6c8dba2b5645fd1567696181d54491f58d92569de301d04b721b0e67.png)  


## Interoperability with Numpy

Numpy is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries:

'Matplotlib'  for plotting and visualization
'OpenCV' for image and video processing
'Pandas' for file I/O and data analysis

Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

Here's how we create an array in Numpy:

In [3]:
import numpy as np

x = np.array([[1, 2],[3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [6]:
# Convert the numpy array to a torch tensor.

y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [7]:
# Vefiying that both numpy array an torch tensor have same size.
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert torch tensor to Numpy array using '.numpy()' method of tensor.

In [8]:
# converting a torch tensor to numpy array

z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])